apiVersion: v1
kind: Service
metadata:
  name: wordpress-service
spec:
  selector:
    app: wordpress-service
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP 
      nodePort: 30000
  type: LoadBalancer
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wordpress-onobrerodrigo
  template:
    metadata:
      labels:
        app: wordpress-onobrerodrigo
    spec: 
      containers:
      - name: wordpress-onobrerodrigo
        image: wordpress:php7.4
        ports:
        - containerPort: 80
        env:
        - name: WORDPRESS_DB_HOST
          valueFrom:
            configMapKeyRef:
              name: mariadb-configmap
              key: database_url
        - name: WORDPRESS_DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mariadb-secret-onobrerodrigo
              key: mariadb-root-password
        - name: WORDPRESS_DB_USER
          value: wordpress
        - name: WORDPRESS_DEBUG
          value: "1"